# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# 使用时注意对应好项目
project './TFMDBDemo.xcodeproj'

target 'TFMDBDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # 去除第三方库警告⚠️
  inhibit_all_warnings!
  # Pods for SecretValentine

pod 'FMDB/SQLCipher', '~> 2.7.2'

end
